name: Create Release for nodejs project
on:
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4.2.2
      - name: install dependencies
        run: |
          cd quote-generator/backend
          npm install

      - name: Build project assets
        run: npm run build

      - name: upload static web content
        uses: actions/upload-artifact@v4.6.2
        with:
          name: static-site
          path: quote-generator/backend/.next/

  create-release:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: static-site

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with: 
          filename: site.zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
